version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/:/app/
      - /app/node_modules

  server:
    build:
      context: ./server
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./server/:/app/
      - /app/node_modules

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
