version: "3"
services:
  client:
    build: ./client/
    ports:
      - 3000:3000
    volumes:
      - /client/node_modules
      - ./client:/client
  server:
    build: ./server/
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./server:/server/
      - /server/node_modules

  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB:perntodo
      - POSTGRES_PASSWORD:packers
      - POSTGRES_USER:postgres
